#################################################################################
# THX TO ALL the Hyprwm Development team:					#
# 	- thx to vaxry for having created and developping this incredible stuff	#
# 	- thx to Mihai Fufezan for supporting him in that			#
# 	- thx to ThatOneCalculator for build and maintain packages		#
# AND THANKS TO ALL THE CONTRIBUTORS OF THE PROJECT!!!				#
#################################################################################

# Written from scratch by likalium :)
# But note that I read the wiki (https://wiki.hyprland.org/) all along the creation of this conf
# Hyprland: https://hyprland.org/

# Note: If an option is empty, it means that I want to ensure that is empty. If something not appears in the config file, it means that I want to keep the default conf (or it's because I missed it but LA LA LA I CAN'T HEAR YOU)

monitor=,highres,auto,1

#defining custom variables
$HOME=/home/likalium
$mainMod=SUPER # I configured that in case I want to change my mainMod key for, for example, ALT
$secondMod=ALT # Same reason as above
$thirdMod=CTRL # Same as above
$fourthMod=Shift_L

#Exec on startup
exec-once=swww init & swww img ~/Documents/lika/wallpapers/deviantart/jadusable_by_kawacy_d7dngmy.jpg
exec-once=swayidle & firefox & cloudflared proxy-dns --port 5553
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once=eww daemon -> not now cuz i haven't yet configured eww widgets
#exec-once=waybar -> if I find the time to make one
exec-once=/usr/bin/lxpolkit
exec-once=hyprctl setcursor Bibata-Modern-Classic 24

# Source the options file
source=$HOME/.config/hypr/hyproptions.conf

# Source the binds
source=$HOME/.config/hypr/hyprbinds.conf

# Source the windowrules
source=$HOME/.config/hypr/hyprrules.conf
