# Written from Scratch by likalium :)
# But note that I read the wiki (https://wiki.hyprland.org/) step to step during the creation of this conf

# Note: If an option is empty (ex: kb_variant = ), it means that I want to ensure that is empty. If it not appears in the config file, it means that I want to keep the default conf (yeah yeah it also can be because I forget it but LA LA LA I CAN'T HEAR YOU)



# Dwindle layout
dwindle {
	pseudotile = true
	#col.group_border_active = rgb(d891de)
	preserve_split = true
}

# Monitors options
# monitor = LVDS-1, 1366x768@60, 0x0, 1

# Workspaces options
# workspace = LVDS-1, 1

# Master layout
master {
	new_is_master=false
	new_on_top=true
}

# General options
general {
	border_size=2
	no_border_on_floating=true
	gaps_in=4
	gaps_out=6
	col.inactive_border=rgba(ffffff00)
	col.active_border=rgb(77999d)
	cursor_inactive_timeout=5

	layout=dwindle
}


# Decoration options
decoration {
	rounding=10
	active_opacity=1.0
	inactive_opacity=1.0
	blur_size=15
	blur_passes=2
	blur_new_optimizations=true
	blur_ignore_opacity=true
	blur_xray=true
	shadow_range=15 # can do a good thing, but need to better understand how it works
	shadow_render_power=3 # same as above
	col.shadow=rgba(1b1d2bff)
	col.shadow_inactive=rgba(1b1d2b00)
	dim_inactive=true
	dim_strength=0.3
}


# Animations options
animations {
	enabled=yes

	# Defining bezier curves
	bezier=openWindow, 0.87, 0, 0.13, 1
	bezier=closeWindow, 0,.94,.26,.99
	bezier=easeInCubic, 0.32, 0, 0.67, 0 
	bezier=easeOutBack, 0.34, 1.56, 0.64, 1
	bezier=easeInOutBack, 0.68, -0.6, 0.32, 1.6
	bezier=easeInOutQuint, 0.83, 0, 0.17, 1
	bezier=easeOutQuint, 0.22, 1, 0.36, 1
	
	# Windows
	animation=windowsIn, 1, 10, easeOutQuint, slide
	animation=windowsOut, 1, 20, easeOutQuint, slide

	# Fades
	animation=fadeIn, 1, 20, easeOutQuint
	animation=fadeOut, 1, 15, easeOutQuint
	animation=fadeSwitch, 1, 10, easeOutQuint
	animation=fadeDim, 1, 20, easeOutQuint

	# Borders
	animation=border, 1, 15, easeOutQuint

	# Workspaces
	animation=workspaces, 1, 10, easeOutQuint, slide
}


# Input Options 
input {
	# Defining keyboard layout
	kb_layout=fr
	kb_variant=
	kb_model=
	kb_options=
	kb_rules=
	# Mouse
	follow_mouse=1
	float_switch_override_focus=1
	sensitivity=0.0
	# Scrolling
	natural_scroll=true
	scroll_method=2fg
	touchpad {
		# Defining touchpad Options
		disable_while_typing=true
		natural_scroll=true
		tap-to-click=true
		middle_button_emulation=true
	}
}


# Gesture Options
gestures {
	workspace_swipe=true
	workspace_swipe_distance=100 # Note: it's in px
	workspace_swipe_fingers=3
	workspace_swipe_create_new=false
	workspace_swipe_forever=true
}

# Binds Options
binds {
	allow_workspace_cycles=true
}

# Misc Options
misc {
	animate_manual_resizes=true
	#cursor_zoom_factor=2.0
}
