# Workspaces
# thx you vaxry for saying me to use wev
# Note that I used codes corresponding to the keys I want to use cause I use AZERTY. So 10 is for 1, 11 for 2, 13 for 3,etc.

# General workspaces
bind=$mainMod,code:10,workspace,1
bind=$mainMod,code:11,workspace,2
bind=$mainMod,code:12,workspace,3
bind=$mainMod,code:13,workspace,4
bind=$mainMod,code:14,workspace,5
bind=$mainMod,code:15,workspace,6
bind=$mainMod,code:16,workspace,7
bind=$mainMod,code:17,workspace,8
bind=$mainMod,code:18,workspace,9


bind=$secondMod,code:10,movetoworkspace,1
bind=$secondMod,code:11,movetoworkspace,2
bind=$secondMod,code:12,movetoworkspace,3
bind=$secondMod,code:13,movetoworkspace,4
bind=$secondMod,code:14,movetoworkspace,5
bind=$secondMod,code:15,movetoworkspace,6
bind=$secondMod,code:16,movetoworkspace,7
bind=$secondMod,code:17,movetoworkspace,8
bind=$secondMod,code:18,movetoworkspace,9

# Enter in "workspaces mode" - Note: yes, i know that inside there's the "default workspaces", but it's wanted
bind=$mainMod,w,submap,workspaces
submap=workspaces

# "Workspaces mode" specific keybinds
bind=$mainMod,s,workspace,name:spotify # useful cuz i let run spotify without watching it
bind=$mainMod,d,workspace,name:discord # it's always open so it's useful too
bind=$mainMod,v,workspace,name:vim #nVim cuz i suppose that it can be useful
bind=$mainMod,m,workspace,name:mpv # Mpv
bind=$mainMod,z,workspace,name:alert


bind=$secondMod,n,movetoworkspace,name:nvim # Nvim cuz a so incredible text editor MUST have his own workspace
bind=$secondMod,m,movetoworkspace,name:mpv # this workspace is my home cinema hehe


bind=$mainMod,s,exec,bash $HOME/.config/hypr/scripts/spotify.sh
bind=$mainMod,d,exec,bash $HOME/.config/hypr/scripts/discord.sh
