return {
	-- Tree-sitter Supported Colorscheme
	{ 'rose-pine/neovim', name = "rose-pine" },
	{ 'shaunsingh/nord.nvim', priority = 1000},
	{ 'catppuccin/nvim', name = "catppuccin", priority = 1000 },
	{ 'decaycs/decay.nvim', config = true },
	{ 'folke/tokyonight.nvim', priority = 1000, config = function() vim.cmd([[colorscheme tokyonight]]) end },
	{ 'navarasu/onedark.nvim' },
	{ 'rafamadriz/neon' },
	{ 'marko-cerovac/material.nvim' },
	{ 'sainnhe/sonokai' },
	{ 'glepnir/zephyr-nvim' },
	{ 'nyoom-engineering/oxocarbon.nvim' },
	{ 'sainnhe/edge' },
	{ 'kyazdani42/blue-moon' },
	{ 'theniceboy/nvim-deus' },
	{ 'bkegley/gloombuddy' },
	{ 'PHSix/nvim-hybrid' },
	{ 'yonlu/omni.vim' },
	{ 'shaunsingh/moonlight.nvim' },
	{ 'Mofiqul/dracula.nvim' },
	{ 'tanvirtin/monokai.nvim' },
	{ 'kaiuri/nvim-juliana' },
	{ 'svrana/neosolarized.nvim' },
	{ 'lourenci/github-colors' },
	{ 'sainnhe/gruvbox-material' },
	{ 'neanias/everforest-nvim' },
	{ 'NTBBloodbath/doom-one.nvim' },
	{ 'hoprr/calvera-dark.nvim' },
	{ 'nxvu699134/vn-night.nvim' },
	{ 'adisen99/codeschool.nvim' },
	{ 'projekt0n/github-nvim-theme' },
	{ 'kdheepak/monochrome.nvim' },
	{ 'FrenzyExists/aquarium-vim' },
	{ 'EdenEast/nightfox.nvim' },
	{ 'kvrohit/substrata.nvim' },
	{ 'ldelossa/vimdark' },
	{ 'Everblush/nvim', name="everblush" },
	{ 'adisen99/apprentice.nvim' },
	{ 'olimorris/onedarkpro.nvim' },
	{ 'rmehri01/onenord.nvim' },
	{ 'luisiacc/gruvbox-baby' },
	{ 'titanzero/zephyrium' }, -- zephyr from glepnir, but improved
	{ 'rebelot/kanagawa.nvim' },
	{ 'tiagovla/tokyodark.nvim' },
	{ 'cpea2506/one_monokai.nvim' },
	{ 'phha/zenburn.nvim' },
	{ 'kvrohit/rasmus.nvim' },
	{ 'ramojus/mellifluous.nvim' },
	{ 'yazeed1s/minimal.nvim' },
	{ 'lewpoly/sherbet.nvim' },
	{ 'Mofiqul/adwaita.nvim' },
	{ 'olivercederborg/poimandres.nvim' },
	{ 'kvrohit/mellow.nvim' },
	{ 'yazeed1s/oh-lucy.nvim' },
	{ 'embark-theme/vim' },
	-- Tree-sitter Supported Colorscheme
	{ 'ellisonleao/gruvbox.nvim' },
}
